services:
  - type: web
    name: syllabus-question-generator
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
